Announce 1.99.11
* All the core infrastructure is now migrated to -core.
* Simplify ins/outs of ref resolver and syntax validator processors.
* Class renaming.
* Some code simplifications.

Francis Galiegue (16):
      Remove SchemaVersion since it is now in -core
      Dictionary: remove .entries()
      Dictionary: remove .missingEntriesFrom()
      Dictionary: remove .valuesForKeys()
      Dictionary: rename .asMap() to .entries()
      Dictionary: remove .get()
      SchemaTree: add .getDollarSchema()
      JsonValidator: remove static extractDollarSchema method
      New class SchemaHolder
      Change inputs/outputs of RefResolverProcessor and SyntaxProcessor
      Make ValidationChain take a RefResolver as an argument
      Rename inputs/outputs to shorter, more meaningful names
      Two code nitpicks
      LoadingConfigurationError: remove an unneeded constructor
      Depend on 0.99.4
      1.99.11