JsonSchemaException: add a constructor with a ValidationMessage argument
Also override the needed methods from Exception so that they behave as expected.

Signed-off-by: Francis Galiegue <fgaliegue@gmail.com>