0.6.0
* Entirely new validation message API. Custom keyword syntax checkers/validators
  are now required to inject a proper message into a validation report.
* Hostname and email validation have recovered their ability to be strictly RFC
  compliant, by enabling a validation feature before building the schema
  factory.
* Threaded testing for syntax checking, keyword validation, full validation.

Francis Galiegue (124):
      Add a ValidationMessage class
      JsonSchemaException: add a constructor with a ValidationMessage argument
      ValidationMessage: make Builder's info an ObjectNode
      ValidationMessage: rename all .info() methods to .addInfo()
      ValidationMessage: add getters
      JsonResolver: make it use ValidationMessage, modify tests accordingly
      ValidationMessage: add .toString() implementation
      Make SyntaxChecker an abstract class
      TypeKeywordSyntaxChecker: add comments to private's .validateOne()
      Make syntax validation as a whole use ValidationMessage
      MiniPerfTest2: separate initial validation from other validations
      Some minor message changes
      Reword message collection code in SyntaxValidator and checkers
      Start to test for message contents -- and make testing thread-safe
      README.markdown: latest version is now 0.5.3
      More message tests for dependencies syntax checking
      Test for syntax validation messages in single/multiple type scenarios
      Add message checking for divisibleBy syntax checking
      Message checks for enum, exclusiveMaximum, exclusiveMinimum
      AbstractSyntaxCheckerTest: add parallel testing
      Message checks for extends
      Make RhinoHelper thread-safe
      Current version is now 0.5.4
      Message tests for pattern, patternProperties and positive integer keywords
      Complete syntax validation message tests
      AbstractKeywordValidatorTest: enable parallel testing
      AbstractSyntaxCheckerTest: remove test for non present messages
      Start and convert keyword validators to use ValidationMessage
      Validation message tests for additionalProperties
      Validation message tests for dependencies, 1/2: simple dependencies
      Simple dependencies report: improve
      Validation message tests for divisibleBy
      KeywordValidator: add a .newMsg() method
      Validation message tests for enum
      Reduce the number of threaded tests invocation
      Validation messages for format, untested...
      NumericKeywordValidator: refactor, part 1
      NumericKeywordValidator: refactor, part 2
      NumericKeywordValidator: refactor, last part
      KeywordValidator: add a JsonNodeFactory static final member
      Validation message tests for minimum and maximum
      Add tests for maxItems keyword
      Fix spelling mistake...
      Add tests for maxLength keyword
      RhinoHelper: broaden try block
      Fix maxLength tests :(
      Tests for the minItems keyword
      Tests for the minLength keyword
      Tests for the pattern keyword
      Tests for the properties keyword
      Tests for the uniqueItems keyword
      TypeKeywordValidator: separate test cases, refactor
      Add message tests for disallow
      Message test for schema dependencies
      Add complete tests for type keyword
      Add tests for extends
      ValidationReport: get rid of String-backed .addMessage{,s}()
      IDEA inspection run
      Work around Jackson's ObjectMapper integer value reading (sort of)
      README.markdown: "announce" 0.6 and validation messages
      JsonValidatorCache: remove one use of ValidationMessage's .defaultBuilder()
      JsonValidatorCache: improve javadoc
      JsonPointer: use ValidationMessage on errors
      Add target file for illegal JSON Pointer messages
      JsonPointerTest: add custom checker for error messages (unused for now)
      JsonPointer{,Test}: straighten out
      Remove remainder information from divisibleBy report message
      URIManager: use ValidationMessage for JsonSchemaException
      ValidationMessage: implement equals()/hashCode()
      SchemaNode: cache hash code
      SchemaContainer: implement hasCode() and equals() too
      Implement .toString() on some core classes
      JsonSchemaException: get rid of the last String constructor user
      JsonSchemaException: add a (ValidationMessage, Exception) constructor
      JsonRef: cache hashCode() value
      JsonPointer: remove unused method
      JsonFragment: make it implement equals()/hashCode() for all its inheritors
      JsonSchemaException: get rid of (String, Exception) constructor
      JsonSchemaException: modify .get*Messages()
      JsonPointerTest: simplify
      PropertiesKeywordValidator: also order the required value set in reports
      Add JavaDoc for ValidationMessage and friends, remove unused code
      IDEA inspections run: minor fixes
      Javadoc's overview: mention the new API possibilities wrt messages
      Push down Comparable<?> implementation to JsonFragment
      JsonFragment: code "clearance"
      Move Validation{Message,Domain,Report} classes to a dedicated package
      Package reorganization (BREAKS EXISTING CODE)
      FormatSpecifier: make it use a ValidationMessage
      Add a URIDownloader for the "resource" scheme
      JsonSchemaFactory: fix misleading Javadoc
      AbstractKeywordValidatorTest: use Guava's Lists
      AbstractSyntaxCheckerTest: use Guava's Lists
      JsonSchemaFactory: get rid of the .getValidatorCache() function
      ValidationReport: make it implement .toString()
      Issue #14: only push/pop the context's container where needed
      README.markdown: 0.5.5
      IDEA inspection run
      JsonSchema: remove an unneeded call
      ValidationContext: implement push()/pop()
      Move two tests to their appropriate package
      ValidationContext: make it responsible to spawn validators
      Get rid of the JsonValidatorCache argument to JsonValidator constructors
      ContainerValidator: instantiate with a JsonNode directly
      ValidationContext: move package
      ValidationContext: revert the queue mechanism
      InstanceValidator: minor code change
      FormatSpecifier: refactoring, part 1
      FormatSpecifier: refactoring, part 2
      AbstractFormatSpecifierTest: also make tests multithreaded
      FormatKeywordValidator: cleanup...
      FormatSpecifier: refactoring, part 3
      New enum for validation features
      JsonSchema: remove the container instance member
      JsonSchema: take a SchemaNode as a constructor argument
      JsonSchemaFactory: add a ValidationFeature enumset instance member
      ValidationContext: "factorize" constructors
      JsonSchema{,Factory}: pass down the features enumset down to the context
      Implement strict RFC compliance for email and host-name format specifiers
      Document the new validation feature, and rename it
      Javadoc updates
      HostnameFormatSpecifier: fix tests...
      IDEA inspection run, plus import optimization
      Fix Javadoc warnings

gitgrimbo (1):
      Tests for relative schema loading

Signed-off-by: Francis Galiegue <fgaliegue@gmail.com>