Announce 1.99.6
* Package reorganization.
* Some Javadoc completed for already frozen parts.
* Allow easy processing exception customization; use it in existing processors.
* More tests and strenghtening of the core API.
* Create a new schema loading related configuration; use it in one core
  component.

Francis Galiegue (30):
      Announce 1.99.5
      Announce 1.6.0
      Some minor fixes
      Move packages around to more sane namespaces
      Javadoc, javadoc and more javadoc
      Report API small changes
      Rework .toString() for schema/instance trees
      Method renaming
      Start to rework exceptions
      Change exception construction in AbstractProcessingReport
      Test SyntaxProcessor's new "exception ability"
      ProcessorSelector: replace building method with inner class
      library/: prepare for user customization
      IDEA inspection run
      Minor code cleanups
      Remove some unused resource files
      JacksonUtils: get rid of .emptyObject()
      Change processing exception handling, part 1
      Change processing exception handling, part 2
      DictionaryBuilder: disallow null keys and/or values; add tests
      Add unchecked exception classes for misconfigurations
      ProcessingException: test, and make all messages fatal
      Start to create LoadingConfiguration, plus tests
      Basic tests for ProcessingConfigurationError
      LoadingConfiguration: handle namespace setting, plus tests
      More tests for LoadingConfiguration, and fix a bug
      LoadingConfiguration: handle schema redirects
      LoadingConfiguration: more tests, including one which has never been done
      URIManager: make it use LoadingConfiguration
      1.99.6

Signed-off-by: Francis Galiegue <fgaliegue@gmail.com>