Announce 1.99.0
ChangeLog:

* Add syntax checking for the "definitions" keyword.
* Bump JSON Pointer support to version 9.
* Start complete refactoring: stateful JSON trees and schema trees, processing
  context, processors, reports, exceptions; start with ref resolving.

Francis Galiegue (86):
      Announce 1.5.4, 1.4.8
      JsonPointer: code changes
      Reorganize imports
      Rename SchemaContainer to SchemaContext
      ValidationContext: use a queue for contexts
      ValidationReport: use JsonPointer.empty()
      ValidationReport: use a Deque and pushd()/popd() methods
      ValidationContext: add a currentContext instance variable
      Vocabulary change: container -> schema context
      Add a simple JsonTree object
      Start to code a JsonSchemaTree
      Add failing URI scope calculation test
      JsonSchemaTree: add a private "idFromNode" method
      Make URI scope calculation work
      JsonSchemaTree: make popd work!
      JsonSchemaTree: add a .resolve() function
      JsonSchemaTree: also make other .push() versions work... Oops...
      Test array element/object member push in a JSON Schema tree
      Add corner case tests to tree.json
      JsonFragment: get rid of EMPTY, add .isPointer()
      JsonPointer: make .asElements() return a List
      JsonSchemaTree: create a .contains() method, implement in Canonical
      Start to implement, and test, InlineSchemaTree
      Some more code changes in JsonFragment and derivates
      Move JsonTree and derivates to their own package
      JsonPointer: add a .isParentOf() function
      Add Javadoc
      Update draft v4 schema
      Add a .retrieve() function to JsonSchemaTree, implement for canonical tree
      JsonPointer: create a private static builder function
      Add retrieval testing for InlineSchemaTree
      JsonPointer: add a .relativize() function, test that it works
      InlineSchemaTree: make ref lookup work in all cases
      JsonPointer: improve Javadoc
      JSON Pointer: bump to version 9
      JsonTree: add documentation, rename methods
      JsonSchemaTree: add Javadoc
      Document JsonSchemaTree and derivates
      JsonTree: add a getter for the current pointer into the tree
      Make JsonTree and JsonSchemaTree into interfaces
      Start and implement the new message API
      ProcessingMessage: make the (currently only) test pass
      JsonSchemaTree: add a .getLoadingRef() method, implement it
      ProcessingMessage: ensure a schema context is correctly loaded when there is one
      Rename pointer field in processing message
      ProcessingMessage: add .toString()
      Add many processing classes -- but not the essential one
      Simplify processing context logs
      ProcessingMessage: remove Json{,Schema}Tree arguments
      ProcessingMessage: handle nulls, add methods, test
      ProcessingMessage: reorganize code
      Add an AsJson interface
      JsonSchemaTree and derivates: modify interface/implementations
      InlineSchemaTree: fix blatant error :/
      Start to rewrite JsonSchemaTree tests
      JsonSchemaTree test rewrites, continued
      ProcessingContext: add a .newMessage() method
      ProcessingException: add constructors
      Add a ProcessingReport class
      Add JsonSchemaContext
      JsonTree and up: modify some code
      JsonSchemaTree: add a .setPointer() method
      Test the good behaviour of JsonSchemaTree's .setPointer()
      More code changes to JsonTree and derivates
      Port URIManager to the new architecture
      Port SchemaRegistry to the new architecture (as SchemaLoader)
      New interface Processor, start to implement and test ref resolving
      RefResolverProcessor: cleanup code, change return type
      RefResolverProcessor: some new tests
      Add GeoJSON schemas for test purposes
      InlineSchemaTree: fix bug in .containsRef()
      InlineSchemaTreeTest: more corner case tests
      JsonTree and derivates: remove .append() of String and int
      JsonTree: modify documentation
      Minor code changes
      Complete rewrite of ref resolver processing tests
      Extract Dereferencing enum out of ref resolving test
      Make JsonSchemaTree an abstract class
      JsonSchemaTree: use the Dereferencing enum
      InlineSchemaTree: add FIXME comment about schema array keywords
      Add test proving the existence of issue #35
      Fix issue #35
      Announce 1.4.9
      Next version will be 1.99.0
      Add syntax checking for "definitions"
      1.99.0

Signed-off-by: Francis Galiegue <fgaliegue@gmail.com>